[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/transcript-proxy"
  to = "/.netlify/functions/fetch-transcript"
  status = 200

[dev]
  command = "npm run dev"
  port = 5000
