[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.71.0",
    "google-api-python-client>=2.185.0",
    "youtube-transcript-api>=1.2.3",
]
